# title of website

title: MyBookMark

# description of website
description: betterworld-liuser's navigation site

# favicon of website
favicon: "https://github.com/betterworld-liuser.png?size=40"

# your website url

url: https://betterworld-liuser.github.io/MyBookMark/

# github profile url
github: "https://github.com/betterworld-liuser"

# footer message

footer: © 2021-2022 @betterworld-liuser

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 影视网站
      sites:
        - name: 注视影视
          description: 没有广告，高清。
          url: https://gaze.run/
        - name: 哔滴影视
          description: 有些广告，但也高清
          url: https://www.btbdys.com/
          - name: 影视大全
          description: 没有广告
          url: https://www.ekvod.com/
          - name: 电影先生
          description: 没有广告
          url: http://dianying.im/
          - name: 白嫖者联盟
          description: 没有广告
          url: https://www.baipiaozhe.com/
          - name: 奈菲电影
          description: 没有广告
          url: https://yanetflix.com/

    - name: Fly
      sites:
        - name: 我们所向往的
          description: 我常用的机场
          url: https://wmsxwd-e.men/auth/register?code=Qz1B
    - name: 网盘分享
      sites:
        - name: 阿里小站
          description: 阿里云盘分享第一名的站点
          url: https://newxiaozhan.com/